endpoints:
  - names : &sampler-endpoints "orion-[01-08]-[10002]"
    group : samplers
    hosts : &sampler-hosts "orion-[01-08]"
    ports : &sampler-ports "[10002]"
    xprt : sock
    auth :
      name  : munge
      config  :
        domain : samplers

  - names : &l1-agg-endpoints "agg[1-3]" 
    group : &l1-agg "l1-agg"
    hosts : &agg-host "ovs-5416"
    ports : "[10101-10103]"
    xprt : sock
    auth :
      name  : munge
      config  :
        domain : aggregators

  - names : &l2-agg-endpoints "agg-4"
    group : &l2-agg "l2-agg"
    hosts : *agg-host
    ports : "10104"
    xprt : sock
    auth :
      name  : munge
      config  :
        domain : users

groups:
  - endpoints : *sampler-endpoints
    name : samplers
    interfaces : 
      - *sampler-hosts

  - endpoints : *l1-agg-endpoints
    name : *l1-agg
    interfaces : 
      - *sampler-hosts
      - *l1-agg-endpoints
      - *l2-agg-endpoints

  - endpoints : *l2-agg-endpoints
    name : *l2-agg
    interfaces :
      - *l1-agg-endpoints
      - *l2-agg-endpoints

aggregators:
  - names     : *l1-agg-endpoints
    endpoints : *l1-agg-endpoints
    group     : *l1-agg

  - names     : *l2-agg-endpoints
    endpoints : *l2-agg-endpoints
    group     : *l2-agg

producers:
# This informs the L1 load balance group what is being distributed across
# the L1 aggregator nodes
  - names     : *sampler-endpoints
    endpoints : *sampler-endpoints
    group     : *l1-agg
    reconnect : 20s
    type      : active
    updaters  :
      - l1-all

  - names     : *l1-agg-endpoints
    endpoints : *l1-agg-endpoints
    group     : *l2-agg
    reconnect : 20s
    type      : active
    updaters  :
      - l2-all

samplers:
  - names       : *sampler-endpoints
    group : samplers
    config :
      - name        : meminfo # Variables can be specific to plugin
        interval    : "1.0s:0ms" # Interval:offset format. Used when starting the sampler plugin
        perm        : "0777"

      - name        : vmstat
        interval    : "1.0s:0ms"
        perm        : "0777"

      - name        : procstat
        interval    : "1.0s:0ms"
        perm        : "0777"
 
      - name        : dstat # Variables can be specific to plugin
        interval    : "1.0s:0ms" # Interval:offset format. Used when starting the sampler plu
        instance    : "agg-${HOSTNAME}" 
        schema      : "agg-dstat" 
        producer    : "ib1-${HOSTNAME}"
        component_id: 23b

updaters:            
- name  : all           # must be unique within group
  group : *l1-agg
  interval : "1.0s:0ms"
  sets :
    - regex : .*        # regular expression matching set name or schema
      field : inst      # 'instance' or 'schema'
  producers :
    - regex : .*        # regular expression matching producer name
                        # this is evaluated on the Aggregator, not
                        # at configuration time'
- name  : all           # must be unique within group
  group : *l2-agg
  interval : "1.0s:0ms"
  sets :
    - regex : meminfo        # regular expression matching set name or schema
      field : inst      # 'instance' or 'schema'
  producers :
    - regex : .*

stores :
  - name      : sos-meminfo
    group     : *l2-agg
    container : ldms_data
    schema    : meminfo
    plugin :
      name   : store_sos
      config : { path            : /DATA15/orion,
                 commit_interval : 600
      }

  - name      : sos-vmstat
    group     : *l2-agg
    container : ldms_data
    schema    : vmstat
    plugin :
      name   : store_sos
      config : { path : /DATA15/orion }

  - name      : sos-procstat
    group     : *l2-agg
    container : ldms_data
    schema    : procstat
    plugin :
      name   : store_sos
      config : { path : /DATA15/orion }

  - name : csv
    group     : *l2-agg
    container : ldms_data
    schema    : meminfo
    plugin :
      name : store_csv
      config :
        path        : /DATA15/orion/csv/orion
        altheader   : 0
        typeheader  : 1
        create_uid  : 3031
        create_gid  : 3031
